// SEARCH INPUT HANDLER
export const SEARCH_INPUT_SAGA = 'SEARCH_INPUT_SAGA';
export const SEARCH_INPUT_FAIL = 'SEARCH_INPUT_FAIL';
// GETTING SHOP AND CONTACT DATA FROM SERVER
export const GET_CONTACT_DATA_SAGA = 'GET_CONTACT_DATA_SAGA';
export const GET_CONTACT_DATA_OK = 'GET_CONTACT_DATA_OK';
export const GET_CONTACT_DATA_FAIL = 'GET_CONTACT_DATA_FAIL';
export const GET_SHOP_DATA_SAGA = 'GET_SHOP_DATA_SAGA';
export const GET_SHOP_DATA_OK = 'GET_SHOP_DATA_OK';
export const GET_SHOP_DATA_FAIL = 'GET_SHOP_DATA_FAIL';
// ON SHOP FORM SEND HANDLER
export const SEND_SHOP_FORM_TO_SERVER_SAGA = 'SEND_SHOP_FORM_TO_SERVER_SAGA';
export const SEND_SHOP_FORM_TO_SERVER_OK = 'SEND_SHOP_FORM_TO_SERVER_OK';
export const SEND_SHOP_FORM_TO_SERVER_FAIL = 'SEND_SHOP_FORM_TO_SERVER_FAIL';
// GETTING TICKETS DATA FROM SERVER
export const GET_TICKETS_DATA_SAGA = 'GET_TICKETS_DATA_SAGA';
export const GET_TICKETS_DATA_OK = 'GET_TICKETS_DATA_OK';
export const GET_TICKETS_DATA_FAIL = 'GET_TICKETS_DATA_FAIL';
// TICKETS POST GET EXTRA CONTENT
export const ON_TICKETS_POST_GET_EXTRA_CONTENT_SAGA = 'ON_TICKETS_POST_GET_EXTRA_CONTENT_SAGA';
export const ON_TICKETS_POST_GET_EXTRA_CONTENT_OK = 'ON_TICKETS_POST_GET_EXTRA_CONTENT_OK';
export const ON_TICKETS_POST_GET_EXTRA_CONTENT_FAIL = 'ON_TICKETS_POST_GET_EXTRA_CONTENT_FAIL';
// TICKETS POST SEARCH SERVER
export const ON_TICKETS_POST_SEARCH_SERVER_SAGA = 'ON_TICKETS_POST_SEARCH_SERVER_SAGA';
export const ON_TICKETS_POST_SEARCH_SERVER_OK = 'ON_TICKETS_POST_SEARCH_SERVER_OK';
export const ON_TICKETS_POST_SEARCH_SERVER_FAIL = 'ON_TICKETS_POST_SEARCH_SERVER_FAIL';
// ON TICKETS NEXTPAGE HANDLER
export const ON_TICKETS_NEXTPAGE_SAGA = 'ON_TICKETS_NEXTPAGE_SAGA';
export const ON_TICKETS_NEXTPAGE_OK = 'ON_TICKETS_NEXTPAGE_OK';
export const ON_TICKETS_NEXTPAGE_FAIL = 'ON_TICKETS_NEXTPAGE_FAIL';
// GETTING TRIPS DATA FROM SERVER
export const GET_TRIPS_DATA_SAGA = 'GET_TRIPS_DATA_SAGA';
export const GET_TRIPS_DATA_OK = 'GET_TRIPS_DATA_OK';
export const GET_TRIPS_DATA_FAIL = 'GET_TRIPS_DATA_FAIL';
// TICKETS POST GET EXTRA CONTENT
export const ON_TRIPS_POST_GET_EXTRA_CONTENT_SAGA = 'ON_TRIPS_POST_GET_EXTRA_CONTENT_SAGA';
export const ON_TRIPS_POST_GET_EXTRA_CONTENT_OK = 'ON_TRIPS_POST_GET_EXTRA_CONTENT_OK';
export const ON_TRIPS_POST_GET_EXTRA_CONTENT_FAIL = 'ON_TRIPS_POST_GET_EXTRA_CONTENT_FAIL';
// TRIPS POSTS SEARCH SERVER
export const ON_TRIPS_POST_SEARCH_SERVER_SAGA = 'ON_TRIPS_POST_SEARCH_SERVER_SAGA';
export const ON_TRIPS_POST_SEARCH_SERVER_OK = 'ON_TRIPS_POST_SEARCH_SERVER_OK';
export const ON_TRIPS_POST_SEARCH_SERVER_FAIL = 'ON_TRIPS_POST_SEARCH_SERVER_FAIL';
//ON TRIPS NEXTPAGE HANDLER
export const ON_TRIPS_NEXTPAGE_SAGA = 'ON_TRIPS_NEXTPAGE_SAGA';
export const ON_TRIPS_NEXTPAGE_OK = 'ON_TRIPS_NEXTPAGE_OK';
export const ON_TRIPS_NEXTPAGE_FAIL = 'ON_TRIPS_NEXTPAGE_FAIL';
